import ed25519 from '@trashman/ed25519-blake2b'

import db from '#db'

/**
 * Creates a new user with a public/private key pair
 * @param {Object} user_data - Optional user data to override defaults
 * @param {string} user_data.username - Username (required)
 * @param {string} [user_data.email] - Email address
 * @param {Buffer} [user_data.private_key] - Optional private key (generated if not provided)
 * @param {string} [user_data.user_id] - Optional user ID (generated by database if not provided)
 * @returns {Object} User information including private_key and user database record
 * @throws {Error} If username is not provided
 */
export default async function create_user({
  username,
  email = 'user@example.com',
  private_key,
  user_id
} = {}) {
  if (!username) {
    throw new Error('Username is required')
  }

  if (!private_key) {
    throw new Error('Private key is required')
  }

  if (!(private_key instanceof Buffer)) {
    private_key = Buffer.from(private_key, 'hex')
  }

  const public_key = ed25519.publicKey(private_key)
  const data = {
    public_key: public_key.toString('hex'),
    username,
    email
  }

  // Add user_id to data if provided
  if (user_id) {
    data.user_id = user_id
  }

  const [{ user_id: created_user_id }] = await db('users')
    .insert(data)
    .returning('user_id')
  const user = await db('users').where('user_id', created_user_id).first()

  return {
    private_key,
    ...user
  }
}
