import ed25519 from '@trashman/ed25519-blake2b'
import { randomUUID } from 'crypto'
import user_registry from './user-registry.mjs'

/**
 * Creates a new user with a public/private key pair
 * @param {Object} user_data - Optional user data to override defaults
 * @param {string} user_data.username - Username (required)
 * @param {string} [user_data.email] - Email address
 * @param {Buffer} [user_data.private_key] - Optional private key (generated if not provided)
 * @param {string} [user_data.user_id] - Optional user ID (generated by database if not provided)
 * @returns {Object} User information including private_key and user database record
 * @throws {Error} If username is not provided
 */
export default async function create_user({
  username,
  email = 'user@example.com',
  private_key,
  user_id
} = {}) {
  if (!username) {
    throw new Error('Username is required')
  }

  if (!private_key) {
    throw new Error('Private key is required')
  }

  if (!(private_key instanceof Buffer)) {
    private_key = Buffer.from(private_key, 'hex')
  }

  const public_key = ed25519.publicKey(private_key)

  // Generate user_id if not provided
  const created_user_id = user_id || randomUUID()

  const user_data = {
    user_id: created_user_id,
    public_key: public_key.toString('hex'),
    username,
    email,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }

  // Add user to registry for testing purposes
  const users = await user_registry.load_users()
  users[public_key.toString('hex')] = {
    username,
    created_at: new Date().toISOString(),
    permissions: {}
  }
  await user_registry.save_users(users)

  return {
    private_key,
    public_key: public_key.toString('hex'),
    user_id: created_user_id, // For backward compatibility in tests
    username,
    created_at: user_data.created_at
  }
}
