/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

import path from 'path'
import webpack from 'webpack'
import HtmlWebpackPlugin from 'html-webpack-plugin'
import CircularDependencyPlugin from 'circular-dependency-plugin'
import config from '#config'

import base from './webpack.base.babel.mjs'

export default base({
  mode: 'development',

  // Add hot reloading in development
  entry: [path.join(process.cwd(), 'client/index.js')],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    publicPath: '/'
  },

  optimization: {
    splitChunks: {
      chunks: 'all'
    }
  },

  // Add development plugins
  plugins: (() => {
    // Validate that paths are configured (no hardcoded fallbacks)
    const user_base_dir =
      process.env.USER_BASE_DIRECTORY || config.user_base_directory
    const system_base_dir =
      process.env.SYSTEM_BASE_DIRECTORY || config.system_base_directory

    if (!user_base_dir) {
      throw new Error(
        'user_base_directory must be set in config or USER_BASE_DIRECTORY env var'
      )
    }
    if (!system_base_dir) {
      throw new Error(
        'system_base_directory must be set in config or SYSTEM_BASE_DIRECTORY env var'
      )
    }

    return [
      new HtmlWebpackPlugin({
        inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
        template: 'client/index.html',
        favicon: 'static/favicon.ico'
      }),
      new webpack.DefinePlugin({
        IS_DEV: true,
        USER_BASE_DIRECTORY: JSON.stringify(user_base_dir),
        SYSTEM_BASE_DIRECTORY: JSON.stringify(system_base_dir)
      }),
      new CircularDependencyPlugin({
        exclude: /a\.js|node_modules/, // exclude node_modules
        failOnError: false // show a warning when there is a circular dependency
      })
    ]
  })(),

  watchOptions: { ignored: '**/node_modules/**' },

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',

  performance: {
    hints: false
  }
})
