services:
  base-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-container
    restart: unless-stopped
    environment:
      - GIT_AUTHOR_NAME=trashman
      - GIT_AUTHOR_EMAIL=trashman@users.noreply.github.com
      - GIT_COMMITTER_NAME=trashman
      - GIT_COMMITTER_EMAIL=trashman@users.noreply.github.com
