services:
  base-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: base-container:latest
    pull_policy: never
    container_name: base-container
    init: true
    restart: unless-stopped
